---
title: "Final Report"
subtitle: "Experiments and Causality"
author: "Colby Carter, Abhishek Agarwal, Tiffany Jaya"
date: \today
output: pdf_document
---

## Load the libraries

```{r, message=FALSE}
library(data.table) # fread
library(dplyr)
library(lmtest) # coeftest
library(lubridate) # time conversion
library(sandwich) # vcovHC
library(RJSONIO)
```

## Helper functions

```{r}
convert_fctr_to_boolean <- function(col) {
  return(as.numeric(as.logical(col)))
}

convert_fctr_to_datetime <- function(col) {
  return(as.POSIXct(col, format="%Y-%m-%d %H:%M:%S"))
}

convert_fctr_to_numeric <- function(col) {
  return(as.numeric(levels(col)[col]))
}

convert_fctr_to_str <- function(col) {
  return(as.character(col))
}

freegeoip <- function(ip, format = ifelse(length(ip)==1,'list','dataframe'))
{
    if (1 == length(ip))
    {
        # a single IP address
        url <- paste(c("http://api.ipstack.com/", ip, "?access_key=0e93a4defcd645bd8829ad75a7223437&output=json&legacy=1/"), collapse='')
        ret <- fromJSON(readLines(url, warn=FALSE))
        if (format == 'dataframe')
            ret <- data.frame(t(unlist(ret)))
        return(ret)
    } else {
        ret <- data.frame()
        for (i in 1:length(ip))
        {
            r <- freegeoip(ip[i], format="dataframe")
            ret <- bind_rows(ret, r)
        }
        return(ret)
    }
}   

try.ip <- function(ip) {
  suppressWarnings(try(freegeoip(ip), silent = TRUE))
}
```

## Load the dataset

```{r}
# pilot study
d <- read.csv(file = "./W241 Colby Carter, Tiffany Jaya, Abhishek Agarwal_April 5, 2018_00.27.csv",
              header = TRUE, 
              sep = ",")
```

```{r}
# actual study
d <- read.csv(file = "./W241 Colby Carter, Tiffany Jaya, Abhishek Agarwal_April 12, 2018_09.41.csv",
              header = TRUE, 
              sep = ",")
```

## Clean up the dataset

**WARNING: DO NOT RERUN THIS SECTION TWICE!**

```{r}
# rename columns to be more descriptive
setnames(d, 
         old = c("Q1.1", 
                 "Q2.2_1",
                 "Q2.3_1",
                 "Q2.5_1",
                 "Q2.7_1",
                 "Q3.1_1", 
                 "Q3.3_1",
                 "Q3.5_1",
                 "Q3.7_1",
                 "Q4.1",
                 "Q4.2",
                 "Q4.3",
                 "Q4.4",
                 "Q4.5",
                 "Q4.6",
                 "Q4.7",
                 "Q4.8",
                 "Q4.9",
                 "Q4.10",
                 "Q4.11",
                 "Q4.12",
                 "Q4.13",
                 "Q4.14",
                 "Q4.15",
                 "Q4.16"),
         new = c("consent", 
                 "control_employment",
                 "control_education", # baseline
                 "control_retirement",
                 "control_cybersecurity",
                 "treatment_employment",
                 "treatment_education", # baseline,
                 "treatment_retirement",
                 "treatment_cybersecurity",
                 "gender",
                 "age",
                 "highest_education",
                 "employment_status",
                 "marital_status",
                 "zip_code",
                 "community", # rural, urban, suburban
                 "can_vote",
                 "political_party",
                 "ethnicity",
                 "income",
                 "have_kids",
                 "internet_from_mobile",
                 "internet_from_home",
                 "internet_from_work",
                 "who_pays_internet"))
```

```{r}
# 1. remove the first two rows
d <- tail(d, -2)
# 2. remove rownames to avoid confusion (because it is not the subject's id)
rownames(d) <- NULL
# 3. safely convert columns of type factors to their respective types
# 3a. factor -> datetime
cols <- c("StartDate", "EndDate", "RecordedDate")
d[,cols] <- lapply(d[,cols], convert_fctr_to_datetime)
# 3b. factor -> logical/boolean
cols <- c("Finished")
d[,cols] <- lapply(d[,cols], convert_fctr_to_boolean)
d$consent <- ifelse(d$consent == "Yes", 1, 0)
d$can_vote <- ifelse(d$can_vote == "Yes", 1, 0)
d$have_kids <- ifelse(d$have_kids == "Yes", 1, 0)
# 3c. factor -> numeric
cols <- c("Progress", "Duration..in.seconds.", "LocationLatitude", "LocationLongitude",
          "control_employment", "control_education", "control_retirement", "control_cybersecurity",
          "treatment_employment", "treatment_education", "treatment_retirement", "treatment_cybersecurity",
          "zip_code")
d[,cols] <- lapply(d[,cols], convert_fctr_to_numeric)
# 3d. factor -> str
cols <- c("IPAddress", "ResponseId", "UserLanguage")
d[,cols] <- lapply(d[,cols], convert_fctr_to_str)
```

```{r}
d
```


## List all the columns

```{r}
colnames(d)
```

## Analysis

```{r}
# how many subjects take the survey?
nrow(d)
```

```{r out.width="49%", fig.align="center", fig.show="hold"}
# how many subjects did not finish the survey?
sum(!d$Finished)

hist(d$Progress, 
     xlab = "progress (%)",
     ylab = "number of users",
     breaks = -0.5:100.5, 
     ylim = c(0, 700),
     labels = TRUE)
```

```{r out.width="49%", fig.align="center", fig.show="hold"}
# how long does it take the subjects to finish the survey in minutes?
summary(d$Duration..in.seconds./60)
```

```{r}
# list all subjects who did not consent
subjects.no_consent <- d[which(d$consent == 0),]
nrow(subjects.no_consent)
```

```{r}
# list all the subjects who take less than 2 minutes to finish the survey
subjects.less_2_min <- d[which(d$Duration..in.seconds./60 < 2),]
nrow(subjects.less_2_min)
```

```{r}
# verify that the subjects who did not consent 
# match the subjects who took the survey less than 2 minutes
all(subjects.less_2_min$ResponseId %in% subjects.no_consent$ResponseId)
```

```{r}
# list all languages not in English
d[which(d$UserLanguage != "EN"),]$UserLanguage
```

```{r}
# get information about the ips
#(ips <- try.ip(d$IPAddress))
```

```{r}
d$IPAddress
```



```{r}
for(i in 1:length(d$IPAddress)) {
  if(i %% 10 == 0){
    
    cat
  }
}
```

```{r}
library(geonames)
lapply(d, function(row) GNCountryCode(row$latitude, row$longitude)$countryName)
```

```{r}
https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=AIzaSyC8Q7FY6SzmEfpMTOcx2BTrnYaRkzX12Ik
```

```{r}
library(revgeo)
revgeo(longitude=-73.961452, latitude=40.714224, output="frame", provider="google", API="AIzaSyC8Q7FY6SzmEfpMTOcx2BTrnYaRkzX12Ik")
```
```{r}

revgeo(longitude = d$LocationLongitude, latitude = d$LocationLatitude, output = "frame", provider = "google", API = "AIzaSyC8Q7FY6SzmEfpMTOcx2BTrnYaRkzX12Ik")
```

## References

1. renaming column names: http://rprogramming.net/rename-columns-in-r/ 


